// Generated by Supabase type generation (helper types at the bottom trimmed). Regenerate after schema changes.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.18"
  }
  public: {
    Tables: {
      body_weights: {
        Row: {
          created_at: string
          id: string
          measured_on: string
          note: string | null
          user_id: string
          weight_kg: number
        }
        Insert: {
          created_at?: string
          id?: string
          measured_on: string
          note?: string | null
          user_id?: string
          weight_kg: number
        }
        Update: {
          created_at?: string
          id?: string
          measured_on?: string
          note?: string | null
          user_id?: string
          weight_kg?: number
        }
        Relationships: []
      }
      diary_days: {
        Row: {
          log_date: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          log_date: string
          status: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          log_date?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      food_logs: {
        Row: {
          amount: number
          carbs_g: number | null
          cost_minor: number | null
          cost_status: string
          created_at: string
          currency: string | null
          energy_kcal: number | null
          fat_g: number | null
          fiber_g: number | null
          food_brand: string | null
          food_id: string | null
          food_name: string
          id: string
          log_date: string
          meal_slot: string
          price_id: string | null
          protein_g: number | null
          resolved_grams: number | null
          resolved_ml: number | null
          saturated_fat_g: number | null
          serving_id: string | null
          serving_label: string | null
          sodium_mg: number | null
          sugar_g: number | null
          unit: string
          updated_at: string
          user_id: string
        }
        Insert: {
          amount: number
          carbs_g?: number | null
          cost_minor?: number | null
          cost_status: string
          created_at?: string
          currency?: string | null
          energy_kcal?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          food_brand?: string | null
          food_id?: string | null
          food_name: string
          id?: string
          log_date: string
          meal_slot: string
          price_id?: string | null
          protein_g?: number | null
          resolved_grams?: number | null
          resolved_ml?: number | null
          saturated_fat_g?: number | null
          serving_id?: string | null
          serving_label?: string | null
          sodium_mg?: number | null
          sugar_g?: number | null
          unit: string
          updated_at?: string
          user_id?: string
        }
        Update: {
          amount?: number
          carbs_g?: number | null
          cost_minor?: number | null
          cost_status?: string
          created_at?: string
          currency?: string | null
          energy_kcal?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          food_brand?: string | null
          food_id?: string | null
          food_name?: string
          id?: string
          log_date?: string
          meal_slot?: string
          price_id?: string | null
          protein_g?: number | null
          resolved_grams?: number | null
          resolved_ml?: number | null
          saturated_fat_g?: number | null
          serving_id?: string | null
          serving_label?: string | null
          sodium_mg?: number | null
          sugar_g?: number | null
          unit?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "food_logs_food_id_fkey"
            columns: ["food_id"]
            isOneToOne: false
            referencedRelation: "foods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "food_logs_price_id_fkey"
            columns: ["price_id"]
            isOneToOne: false
            referencedRelation: "food_prices"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "food_logs_serving_id_food_id_fkey"
            columns: ["serving_id", "food_id"]
            isOneToOne: false
            referencedRelation: "food_servings"
            referencedColumns: ["id", "food_id"]
          },
        ]
      }
      food_prices: {
        Row: {
          created_at: string
          currency: string
          effective_date: string
          food_id: string
          id: string
          package_amount: number
          package_serving_id: string | null
          package_unit: string
          price_minor: number
          store_note: string | null
          user_id: string
        }
        Insert: {
          created_at?: string
          currency: string
          effective_date: string
          food_id: string
          id?: string
          package_amount: number
          package_serving_id?: string | null
          package_unit: string
          price_minor: number
          store_note?: string | null
          user_id?: string
        }
        Update: {
          created_at?: string
          currency?: string
          effective_date?: string
          food_id?: string
          id?: string
          package_amount?: number
          package_serving_id?: string | null
          package_unit?: string
          price_minor?: number
          store_note?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "food_prices_food_id_fkey"
            columns: ["food_id"]
            isOneToOne: false
            referencedRelation: "foods"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "food_prices_package_serving_id_food_id_fkey"
            columns: ["package_serving_id", "food_id"]
            isOneToOne: false
            referencedRelation: "food_servings"
            referencedColumns: ["id", "food_id"]
          },
        ]
      }
      food_servings: {
        Row: {
          food_id: string
          grams: number | null
          id: string
          label: string
          ml: number | null
        }
        Insert: {
          food_id: string
          grams?: number | null
          id?: string
          label: string
          ml?: number | null
        }
        Update: {
          food_id?: string
          grams?: number | null
          id?: string
          label?: string
          ml?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "food_servings_food_id_fkey"
            columns: ["food_id"]
            isOneToOne: false
            referencedRelation: "foods"
            referencedColumns: ["id"]
          },
        ]
      }
      foods: {
        Row: {
          basis_serving_id: string | null
          brand: string | null
          carbs_g: number | null
          created_at: string
          density_g_per_ml: number | null
          energy_kcal: number | null
          fat_g: number | null
          fiber_g: number | null
          id: string
          name: string
          nutrient_basis: string
          owner_id: string | null
          preparation: string
          protein_g: number | null
          saturated_fat_g: number | null
          sodium_mg: number | null
          source: string
          source_id: string | null
          sugar_g: number | null
          updated_at: string
        }
        Insert: {
          basis_serving_id?: string | null
          brand?: string | null
          carbs_g?: number | null
          created_at?: string
          density_g_per_ml?: number | null
          energy_kcal?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          id?: string
          name: string
          nutrient_basis: string
          owner_id?: string | null
          preparation?: string
          protein_g?: number | null
          saturated_fat_g?: number | null
          sodium_mg?: number | null
          source: string
          source_id?: string | null
          sugar_g?: number | null
          updated_at?: string
        }
        Update: {
          basis_serving_id?: string | null
          brand?: string | null
          carbs_g?: number | null
          created_at?: string
          density_g_per_ml?: number | null
          energy_kcal?: number | null
          fat_g?: number | null
          fiber_g?: number | null
          id?: string
          name?: string
          nutrient_basis?: string
          owner_id?: string | null
          preparation?: string
          protein_g?: number | null
          saturated_fat_g?: number | null
          sodium_mg?: number | null
          source?: string
          source_id?: string | null
          sugar_g?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "foods_basis_serving_fk"
            columns: ["basis_serving_id", "id"]
            isOneToOne: false
            referencedRelation: "food_servings"
            referencedColumns: ["id", "food_id"]
          },
        ]
      }
      profiles: {
        Row: {
          activity_level: string | null
          birth_date: string | null
          calorie_floor_kcal: number
          created_at: string
          currency: string
          display_name: string | null
          height_cm: number | null
          sex: string | null
          time_zone: string
          unit_system: string
          updated_at: string
          user_id: string
        }
        Insert: {
          activity_level?: string | null
          birth_date?: string | null
          calorie_floor_kcal?: number
          created_at?: string
          currency?: string
          display_name?: string | null
          height_cm?: number | null
          sex?: string | null
          time_zone?: string
          unit_system?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          activity_level?: string | null
          birth_date?: string | null
          calorie_floor_kcal?: number
          created_at?: string
          currency?: string
          display_name?: string | null
          height_cm?: number | null
          sex?: string | null
          time_zone?: string
          unit_system?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      targets: {
        Row: {
          carbs_g: number
          created_at: string
          effective_from: string
          fat_g: number
          goal_weight_kg: number | null
          id: string
          kcal: number
          kg_per_week: number | null
          protein_g: number
          source: string
          user_id: string
        }
        Insert: {
          carbs_g: number
          created_at?: string
          effective_from: string
          fat_g: number
          goal_weight_kg?: number | null
          id?: string
          kcal: number
          kg_per_week?: number | null
          protein_g: number
          source: string
          user_id?: string
        }
        Update: {
          carbs_g?: number
          created_at?: string
          effective_from?: string
          fat_g?: number
          goal_weight_kg?: number | null
          id?: string
          kcal?: number
          kg_per_week?: number | null
          protein_g?: number
          source?: string
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  TableName extends keyof DefaultSchema["Tables"],
> = DefaultSchema["Tables"][TableName]["Row"]

export type TablesInsert<
  TableName extends keyof DefaultSchema["Tables"],
> = DefaultSchema["Tables"][TableName]["Insert"]

export type TablesUpdate<
  TableName extends keyof DefaultSchema["Tables"],
> = DefaultSchema["Tables"][TableName]["Update"]
